server:
  port: 9092


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
  application:
    name: HotelService

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka